// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernRecrut.Postulations.API.Data;

#nullable disable

namespace ModernRecrut.Postulations.API.Migrations
{
    [DbContext(typeof(PostulationContext))]
    [Migration("20231129192604_MigrationInitiale")]
    partial class MigrationInitiale
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.24");

            modelBuilder.Entity("ModernRecrut.Postulations.API.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomEmetteur")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostulationID")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostulationID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("ModernRecrut.Postulations.API.Entities.Postulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidatID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDisponibilite")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OffreEmploiID")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PretentionSalariale")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Postulations");
                });

            modelBuilder.Entity("ModernRecrut.Postulations.API.Entities.Note", b =>
                {
                    b.HasOne("ModernRecrut.Postulations.API.Entities.Postulation", null)
                        .WithMany("Notes")
                        .HasForeignKey("PostulationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModernRecrut.Postulations.API.Entities.Postulation", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
